version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: rhc_mariadb_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata_prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30

  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: rhc_hockey_prod
    restart: unless-stopped
    env_file: .env.prod
    environment:
      DJANGO_SETTINGS_MODULE: hockey_club.settings
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      DB_HOST: db
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_PORT: "3306"
      # Ensure STATIC_ROOT in Dockerfile.production matches this path
      STATIC_ROOT: /app/staticfiles
      MEDIA_ROOT: /app/media
    volumes:
      - static_prod:/app/staticfiles
      - media_prod:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn hockey_club.wsgi:application --bind 0.0.0.0:8000 --workers=4 --threads=2 --timeout=60
      "

volumes:
  dbdata_prod:
  static_prod:
  media_prod:
