# Generated by Django 5.2.5 on 2025-08-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0004_backfill_subscription_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="season",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="memberships.season",
            ),
        ),
    ]
