# Generated by Django 5.2.5 on 2025-09-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0005_alter_subscription_season"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-started_at"],
                "permissions": [
                    ("activate_subscription", "Can activate a pending subscription"),
                    (
                        "set_pending_subscription",
                        "Can set a subscription back to pending",
                    ),
                    ("cancel_subscription", "Can cancel a subscription"),
                ],
            },
        ),
    ]
