# Generated by Django 5.2.5 on 2025-09-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("members", "0022_alter_player_membership_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visible_to_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If empty, not restricted by groups.",
                        related_name="calendar_events",
                        to="auth.group",
                    ),
                ),
                (
                    "visible_to_teams",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If empty, not restricted by teams.",
                        related_name="calendar_events",
                        to="members.team",
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
                "permissions": (),
            },
        ),
    ]
