# Generated by Django 5.2.5 on 2025-09-05 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("club_calendar", "0001_initial"),
        ("members", "0022_alter_player_membership_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#3c8dbc",
                        help_text="HEX colour (e.g. #3c8dbc).",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid HEX colour like #1e90ff or #09f",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start"]},
        ),
        migrations.AlterField(
            model_name="event",
            name="visible_to_groups",
            field=models.ManyToManyField(
                blank=True, related_name="calendar_events", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="visible_to_teams",
            field=models.ManyToManyField(
                blank=True, related_name="calendar_events", to="members.team"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="club_calendar.topic",
            ),
        ),
    ]
