# Generated by Django 5.2.5 on 2025-09-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_calendar", "0002_topic_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_recurring",
            field=models.BooleanField(default=False, help_text="Tick to enable recurrence."),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_end",
            field=models.DateTimeField(
                blank=True, help_text="Optional end for recurrence (UNTIL).", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="rrule",
            field=models.TextField(
                blank=True, help_text='iCal RRULE (e.g. "FREQ=WEEKLY;BYDAY=MO,WE").'
            ),
        ),
        migrations.CreateModel(
            name="EventCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurrence_start", models.DateTimeField(db_index=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellations",
                        to="club_calendar.event",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "occurrence_start"],
                        name="club_calend_event_i_f94d1e_idx",
                    )
                ],
                "unique_together": {("event", "occurrence_start")},
            },
        ),
    ]
