# Generated by Django 5.2.5 on 2025-09-05 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "club_calendar",
            "0003_event_is_recurring_event_recurrence_end_event_rrule_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="rrule",
            field=models.TextField(
                blank=True,
                help_text='iCal RRULE generated by the form (e.g. "FREQ=WEEKLY;BYDAY=MO,WE").',
            ),
        ),
        migrations.CreateModel(
            name="EventOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurrence_start",
                    models.DateTimeField(db_index=True, help_text="Original occurrence start"),
                ),
                ("new_start", models.DateTimeField(blank=True, null=True)),
                ("new_end", models.DateTimeField(blank=True, null=True)),
                ("new_title", models.CharField(blank=True, max_length=200)),
                ("new_location", models.CharField(blank=True, max_length=255)),
                ("new_description", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="club_calendar.event",
                    ),
                ),
                (
                    "new_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="club_calendar.topic",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "occurrence_start"],
                        name="club_calend_event_i_c4f5d8_idx",
                    )
                ],
                "unique_together": {("event", "occurrence_start")},
            },
        ),
    ]
