# Generated by Django 5.2.5 on 2025-09-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentlog",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
