# Generated by Django 5.2.5 on 2025-08-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = []
