# Generated by Django 5.2.5 on 2025-08-31 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tasks", "0003_alter_task_options_remove_task_completed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="related_player",
        ),
        migrations.AddField(
            model_name="task",
            name="complete_on",
            field=models.CharField(
                blank=True,
                help_text="When an event with this name is emitted for the same subject, mark this task DONE.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="subject_ct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="subject_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="tasks_task_status_4a0a95_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["subject_ct", "subject_id", "status"],
                name="tasks_task_subject_89ff99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["complete_on"], name="tasks_task_complet_531743_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["subject_ct", "subject_id", "complete_on", "status"],
                name="tasks_task_subject_960d91_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="task",
            table=None,
        ),
    ]
