# Generated by Django 5.2.5 on 2025-08-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spond_integration', '0003_spondevent_spondattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='spondevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spondevent',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spondevent',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spondevent',
            name='meetup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
