# Generated by Django 5.2.5 on 2025-08-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spond_integration", "0006_spondtransaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpondTransaction",
        ),
    ]
