# Generated by Django 5.2.5 on 2025-08-29 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0013_questioncategory_description"),
        ("spond_integration", "0007_delete_spondtransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpondTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("spond_txn_id", models.CharField(max_length=64, unique=True)),
                ("type", models.CharField(blank=True, max_length=32)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("description", models.CharField(blank=True, max_length=512)),
                ("amount_minor", models.IntegerField(default=0)),
                ("currency", models.CharField(default="GBP", max_length=8)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="spond_integration.spondevent",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="spond_integration.spondgroup",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="spond_integration.spondmember",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spond_transactions",
                        to="members.player",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="spond_integ_created_76d5b6_idx"),
                    models.Index(fields=["status"], name="spond_integ_status_29737d_idx"),
                    models.Index(fields=["member"], name="spond_integ_member__f70a79_idx"),
                    models.Index(fields=["player"], name="spond_integ_player__5bd681_idx"),
                ],
            },
        ),
    ]
