# Generated by Django 5.2.5 on 2025-08-31 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spond_integration", "0009_spondevent_is_match_spondevent_kind_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spondaccessanchor",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("access_spond_app", "Has Access to Spond App"),
                    ("link_spond_app", "Has Access to Link player to Spond App"),
                ),
            },
        ),
    ]
