# Generated by Django 5.2.5 on 2025-08-26 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable identifier (e.g. 'medical_conditions')", max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('boolean', 'Checkbox')], default='text', max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('requires_detail_if_yes', models.BooleanField(default=False, help_text='If checkbox is ticked, require additional detail')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('visible_to_groups', models.ManyToManyField(blank=True, related_name='viewable_questions', to='auth.group')),
                ('applies_to', models.ManyToManyField(related_name='questions', to='members.playertype')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('relation', models.CharField(choices=[('self', 'Self'), ('additional_adult', 'Additional adult'), ('child', 'Child (under 18)')], default='self', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
                ('player_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.playertype')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('created_by', 'first_name', 'last_name', 'date_of_birth')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('boolean_answer', models.BooleanField(blank=True, null=True)),
                ('detail_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='members.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='members.dynamicquestion')),
            ],
            options={
                'unique_together': {('player', 'question')},
            },
        ),
    ]
