# Generated by Django 5.2.5 on 2025-08-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_position_team_teammembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Prefer not to say')], default='other', max_length=20),
        ),
    ]
