# Generated by Django 5.2.5 on 2025-08-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_player_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('view_staff_area', 'Can view staff area'), ('view_all_players', 'Can view all players'))},
        ),
    ]
