# Generated by Django 5.2.5 on 2025-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_alter_teammembership_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioncategory",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description or instructions (Markdown supported).",
            ),
        ),
    ]
