# Generated by Django 5.2.5 on 2025-08-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_dynamicquestion_number_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playeranswer",
            name="numeric_answer",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
