# Generated by Django 5.2.5 on 2025-09-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0018_clubnotice_quicklink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClubNotice",
        ),
        migrations.DeleteModel(
            name="QuickLink",
        ),
    ]
