# Generated by Django 5.2.5 on 2025-09-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0020_player_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="membership_number",
            field=models.CharField(
                blank=True,
                help_text="Automatically generated sequential membership number",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
