# Generated by Django 5.2.5 on 2025-09-02 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0022_alter_player_membership_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("incident_datetime", models.DateTimeField()),
                (
                    "location",
                    models.CharField(help_text="Pitch / venue / area", max_length=255),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("match", "Match"),
                            ("training", "Training"),
                            ("other", "Other"),
                        ],
                        default="match",
                        max_length=16,
                    ),
                ),
                (
                    "role_involved",
                    models.CharField(
                        choices=[
                            ("player", "Player"),
                            ("coach", "Coach"),
                            ("umpire", "Umpire"),
                            ("volunteer", "Volunteer"),
                            ("spectator", "Spectator"),
                            ("other", "Other / Unknown"),
                        ],
                        default="player",
                        max_length=16,
                    ),
                ),
                (
                    "age_under_18",
                    models.BooleanField(
                        default=False, help_text="Tick if the injured person is U18"
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("suspected_concussion", models.BooleanField(default=False)),
                (
                    "injury_types",
                    models.CharField(
                        blank=True,
                        help_text="Free text or comma-separated (e.g. ankle sprain, cut)",
                        max_length=255,
                    ),
                ),
                (
                    "treatment_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("first_aid", "First aid specialist"),
                            ("hospital", "Hospital treatment"),
                            ("gp", "Subsequent GP visit"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("first_aider_name", models.CharField(blank=True, max_length=255)),
                ("first_aider_contact", models.CharField(blank=True, max_length=255)),
                (
                    "attachments",
                    models.FileField(blank=True, null=True, upload_to="incidents/%Y/%m/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted (internal)"),
                            ("review", "In Review"),
                            ("action_required", "Action Required"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("status_notes", models.TextField(blank=True)),
                (
                    "submitted_to_eh",
                    models.BooleanField(
                        default=False, help_text="Logged in SportSmart / EH system"
                    ),
                ),
                ("eh_submission_datetime", models.DateTimeField(blank=True, null=True)),
                ("sportsmart_reference", models.CharField(blank=True, max_length=128)),
                ("sportsmart_url", models.URLField(blank=True)),
                (
                    "parents_notified",
                    models.BooleanField(
                        default=False, help_text="For U18, parents/guardians informed"
                    ),
                ),
                ("safeguarding_notified", models.BooleanField(default=False)),
                ("safeguarding_notes", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "primary_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_incidents",
                        to="members.player",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="members.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-incident_datetime", "-id"],
                "permissions": [
                    (
                        "can_action_incident",
                        "Can action incidents (review/escalate/close)",
                    )
                ],
            },
        ),
    ]
