# Generated by Django 5.2.5 on 2025-09-02 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="parents_notified",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="sportsmart_reference",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="sportsmart_url",
        ),
        migrations.AlterField(
            model_name="incident",
            name="age_under_18",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="incident",
            name="injury_types",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted (internal)"),
                    ("review", "In Review"),
                    ("action_required", "Action Required"),
                    ("closed", "Closed"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="submitted_to_eh",
            field=models.BooleanField(default=False, help_text="Logged in EH SportSmart"),
        ),
        migrations.CreateModel(
            name="IncidentRouting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Default incident review team", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="incident_routing_reviewers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
