# Generated by Django 5.2.5 on 2025-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0003_incident_assigned_at_incident_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={
                "ordering": ["-incident_datetime", "-id"],
                "permissions": [
                    ("access_app", "Can Access This App"),
                    ("submit_incident", "Can Submit Incident Report"),
                    ("view_list", "Can See Incident List"),
                    ("view_sensitive", "Can View Sensitive Report"),
                    ("assign_incident", "Can Assign Incident"),
                    ("complete_review", "Can Complete Review"),
                    ("can_delete_incident", "Can Delete Incidents"),
                ],
            },
        ),
        migrations.AddField(
            model_name="incident",
            name="is_sensitive",
            field=models.BooleanField(
                default=False, help_text="Tick if this report contains sensitive information."
            ),
        ),
    ]
