# Generated by Django 5.2.5 on 2025-08-31 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="Task"),
            ],
            database_operations=[],
        ),
    ]
